[features]
seeds = false
skip-lint = false

[toolchain]
anchor_version = "0.32.1"

[programs.localnet]
presale = "9GprBhFEyLipafFmS75rta8HGZTU5WPZRG3tWGJDBrmC"

[programs.devnet]
presale = "9GprBhFEyLipafFmS75rta8HGZTU5WPZRG3tWGJDBrmC"

[programs.mainnet]
presale = "9GprBhFEyLipafFmS75rta8HGZTU5WPZRG3tWGJDBrmC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
