[features]
seeds = false
skip-lint = false

[toolchain]
anchor_version = "0.32.1"

[programs.localnet]
presale = "J6uoJoaYaytU2PRedpzszvMZMmF4aNvAzHeqgtxQu1nN"

[programs.devnet]
presale = "J6uoJoaYaytU2PRedpzszvMZMmF4aNvAzHeqgtxQu1nN"

[programs.mainnet]
presale = "J6uoJoaYaytU2PRedpzszvMZMmF4aNvAzHeqgtxQu1nN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

