[features]
seeds = false
skip-lint = false

[toolchain]
anchor_version = "0.32.1"

[programs.localnet]
presale = "66Qho8H4xsVLBqZNLyvxTwRrgMP319rt5EuN2ZzaFay8"

[programs.devnet]
presale = "66Qho8H4xsVLBqZNLyvxTwRrgMP319rt5EuN2ZzaFay8"

[programs.mainnet]
presale = "66Qho8H4xsVLBqZNLyvxTwRrgMP319rt5EuN2ZzaFay8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

